name: .NET CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
# Build and test on .NET Core
  dotnet-core-ci:
    name: .NET Core - test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install dependencies
        run: nuget restore

      - name: Build solution
        run: dotnet build

      - name: Run tests
        run: dotnet test

      # - name: Run linter
      #   run: dotnet format --verify-no-changes

  # Build and test on .NET Framework
  dotnet-framework-ci:
    name: .NET Framework - test
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@30375c66a4eea26614e0d39710365f22f8b0af57 # v3

      - name: Set up VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Install dependencies
        run: nuget restore

      - name: Build DuoApiTest solution
        run: msbuild.exe duo_api_csharp.sln

      - name: Run Tests dll
        run: vstest.console.exe .\test\bin\Debug\DuoApiTest.dll
