name: .NET CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and test on .NET Framework
  dotnet-framework-ci:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Set up NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Set up VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Install dependencies
        run: nuget restore test/DuoAPiTest.sln

      - name: Build solution
        run: msbuild.exe test/DuoAPiTest.sln

      # - name: Run DuoUniversal.Tests
      #   run: vstest.console.exe .\DuoUniversal.Tests\bin\Debug\net6.0\DuoUniversal.Tests.dll